#!/bin/sh

ENABLED=yes

DESC="HAProxy Exporter"
PROCS="haproxy_exporter"
PROG="/opt/bin/$PROCS"

ARGS="--haproxy.scrape-uri=http://localhost:8404/stats?stats;csv"
PREARGS=""

. /opt/etc/init.d/rc.func
