#!/bin/sh

ENABLED=yes

DESC="DNSCrypt Proxy (2)"
PROCS="dnscrypt-proxy"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

ARGS="-config /opt/etc/$PROCS.toml -pidfile $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
