#!/bin/sh

ENABLED=yes

DESC="Prometheus Alertmanager"
PROCS="alertmanager"
PROG="/opt/bin/$PROCS"

ARGS="--config.file=/opt/etc/prometheus/$PROCS.yml --storage.path=/opt/var/lib/$PROCS"
PREARGS=""

. /opt/etc/init.d/rc.func
