#!/bin/sh

ENABLED=yes

DESC="Web File Browser"
PROCS="filebrowser"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/$PROCS/$PROCS.conf" ] && . /opt/etc/$PROCS/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="$OPTIONS"
PREARGS=""

. /opt/etc/init.d/rc.func
