#!/bin/sh

ENABLED=yes

DESC="v2rayA Service"
PROCS="v2raya"
PROG="/opt/bin/$PROCS"

check_bins() {
  { [ -x "/opt/sbin/v2ray" ] || [ -x "/opt/sbin/xray" ] && return 0 ; } || \
  printf "\033[1;31m %s \033[0m\n" "aborted: v2ray or xray bins not found." && \
  exit 1
}

PRECMD="check_bins"
ARGS="\
-c /opt/etc/$PROCS \
--v2ray-assetsdir /opt/share/v2ray \
--nftables-support off \
--log-file /opt/var/log/$PROCS.log"
PREARGS=""

. /opt/etc/init.d/rc.func
