#!/bin/sh

ENABLED=yes

DESC="Grafana Server"
PROCS="grafana"
PROG="/opt/bin/$PROCS"

CONFIG="/opt/etc/$PROCS/$PROCS.ini"
HOMEPATH="/opt/share/$PROCS"
PID_FILE="/opt/var/run/$PROCS.pid"

ARGS="server -config=$CONFIG -homepath $HOMEPATH -pidfile $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
