#!/bin/sh

ENABLED=yes

DESC="Kopia backup server"
PROCS="kopia"
PROG="/opt/bin/$PROCS"

{ [ -f "/opt/etc/$PROCS/$PROCS.conf" ] && . /opt/etc/$PROCS/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="server start $OPTIONS"
PREARGS=""

. /opt/etc/init.d/rc.func
