#!/bin/sh

ENABLED=yes

DESC="Prometheus monitoring system"
PROCS="prometheus"
PROG="/opt/bin/$PROCS"

FLAGS="\
--config.file=/opt/etc/$PROCS/$PROCS.yml \
--storage.tsdb.path=/opt/var/lib/$PROCS \
--web.console.libraries=/opt/etc/$PROCS/console_libraries \
--web.console.templates=/opt/etc/$PROCS/consoles"

ARGS="$FLAGS"
PREARGS=""

. /opt/etc/init.d/rc.func
