#!/bin/sh

ENABLED=yes

DESC="StatsD Exporter"
PROCS="statsd_exporter"
PROG="/opt/bin/$PROCS"

ARGS="--statsd.mapping-config=/opt/etc/prometheus/statsd_mapping.yml"
PREARGS=""

. /opt/etc/init.d/rc.func
