#!/bin/sh

ENABLED=yes

DESC="Syncthing server"
PROCS="syncthing"
PROG="/opt/bin/$PROCS"

gen_key_config() {
  [ -d "/opt/etc/$PROCS" ] || $PROG generate > /dev/null 2>&1
  if grep -q '127\.0\.0\.1' /opt/etc/$PROCS/config.xml ; then
    sed -i 's|127\.0\.0\.1|0.0.0.0|' /opt/etc/$PROCS/config.xml
  fi
}

PRECMD="gen_key_config"
ARGS="serve"
PREARGS=""

. /opt/etc/init.d/rc.func
