#!/bin/sh

ENABLED=yes

DESC="SFTPGo server"
PROCS="sftpgo"
PROG="/opt/sbin/$PROCS"

ARGS="serve -c /opt/etc/$PROCS -l /opt/var/log/$PROCS.log --log-level error"
PREARGS=""

. /opt/etc/init.d/rc.func
